name: review-system

services:

  mysql-db:
    image: mysql:9.2.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: review_system_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - ./scripts/kube/usersdb-init.sql:/docker-entrypoint-initdb.d/usersdb-init.sql
    networks:
      - review-system-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  postgresql-db:
    image: postgres:17.5
    container_name: postgresql-db
    restart: always
    environment:
      POSTGRES_DB: review_system_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    networks:
      - review-system-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d review_system_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  mongo-db:
    image: mongo:8.0.11
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user123
      MONGO_INITDB_DATABASE: reviewSystemDB
    networks:
      - review-system-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    image: discovery-server:1.0.0
    container_name: discovery-server
    ports:
      - "8080:8080"
    networks:
      - review-system-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    image: config-server:1.0.0
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8081:8085"
    networks:
      - review-system-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: user-service:1.0.0
    container_name: user-service
    depends_on:
      mysql-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    ports:
      - "8082:8081"
    networks:
      - review-system-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  hotel-service:
    build:
      context: .
      dockerfile: hotel-service/Dockerfile
    image: hotel-service:1.0.0
    container_name: hotel-service
    depends_on:
      postgresql-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    ports:
      - "8083:8082"
    networks:
      - review-system-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rating-service:
    build:
      context: .
      dockerfile: rating-service/Dockerfile
    image: rating-service:1.0.0
    container_name: rating-service
    depends_on:
      mongo-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    ports:
      - "8084:8083"
    networks:
      - review-system-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      user-service:
        condition: service_healthy
      hotel-service:
        condition: service_healthy
      rating-service:
        condition: service_healthy
    ports:
      - "8085:8084"
    networks:
      - review-system-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  review-system-network:
    driver: bridge