# Spring Properties
spring:
  application:        # Application Properties
    name: api-gateway
  profiles:           # Profile Properties
    active: @env@
  cloud:              # Cloud Properties
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/users/**
          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/api/v1/ratings/**,/api/v1/ratings/**
          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/api/v1/hotels/**,/api/v1/staffs/**

# Server Properties
server:
  port: 8084

# Management Properties
management:
  endpoint:
    gateway:
      enabled: true