spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  config:
    import: optional:configserver:http://127.0.0.1:8085
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/users/**
          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/api/v1/ratings/**
          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/api/v1/hotels/**,/api/v1/staffs/**

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

server:
  port: 8084