# MongoDB Properties
spring.data.mongodb.uri      = mongodb://127.0.0.1:27017/reviewSystemDB
spring.data.mongodb.username = wulf
spring.data.mongodb.password = wulf123

# Config Properties
spring.config.import = optional:configserver:http://127.0.0.1:8085