# Application Properties
spring.application.name = rating-service

# Profile Properties
spring.profiles.active = @env@

# Threads Properties
spring.threads.virtual.enabled = true

# MongoDB Properties
spring.data.mongodb.uri      = mongodb://127.0.0.1:27017/reviewSystemDB
spring.data.mongodb.username = wulf
spring.data.mongodb.password = wulf123

# Jackson Properties
spring.jackson.default-property-inclusion = non_null

# Cloud Properties
spring.config.import = optional:configserver:http://127.0.0.1:8085

# Eureka Properties
#eureka.instance.prefer-ip-address     = true
#eureka.client.fetch-registry          = true
#eureka.client.register-with-eureka    = true
#eureka.client.service-url.defaultZone = http://127.0.0.1:8080/eureka

# Server Properties
server.port                 = 8083

# Logger Properties
logging.level.root = INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Management Properties
management.endpoints.web.base-path = /actuator
management.endpoints.web.exposure.include = *
management.endpoint.health.show-details = always