# MongoDB Properties
spring.data.mongodb.uri      = mongodb://mongo-db:27017/reviewSystemDB
spring.data.mongodb.username = user
spring.data.mongodb.password = user123

# Config Properties
spring.config.import = optional:configserver:http://config-server:8085