# Application Properties
spring.application.name = user-service

# Profile Properties
spring.profiles.active = @env@

# Datasource Properties
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# Jackson Properties
spring.jackson.default-property-inclusion = non_null

# Server Properties
server.port = 8081