# Datasource Properties
spring.datasource.url               = jdbc:mysql://mysql-db:3306/review_system_db?generateSimpleParameterMetadata=true
spring.datasource.username          = user
spring.datasource.password          = user123

# Config Properties
spring.config.import = optional:configserver:http://config-server:8085