# Spring Properties
spring:
  application:
    name: discovery-server
  threads:
    virtual:
      enabled: true

# Eureka Properties
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

# Server Properties
server:
  port: 8080

# Management Properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    health:
      show-details: always