spring:
  application:
    name: service-registry
  threads:
    virtual:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    health:
      show-details: always