# Spring Properties
spring:
  application:            # Application Properties
    name: hotel-service
  profiles:               # Profile Properties
    active: @env@
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:                    # JPA Properties
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:                # Jackson Properties
    default-property-inclusion: non_null

# Server Properties
server:
  port: 8082